version: "3.9"

services:
  voxpop-core:
    build:
      context: .
      dockerfile: Voxpop.Core/src/Voxpop.Core.Api/Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      ConnectionStrings__CoreDb: Host=postgres;Database=core_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      
      Jwt__Key: ${JWT_KEY}
      
      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341

    depends_on:
      - postgres
      - seq

  voxpop-identity:
    build:
      context: .
      dockerfile: Voxpop.Identity/src/Voxpop.Identity.Api/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}

      ConnectionStrings__IdentityDb: Host=postgres;Database=identity_db;Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      
      Jwt__Key: ${JWT_KEY}
      
      RabbitMq__HostName: rabbitmq
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      
      Serilog__WriteTo__1__Args__serverUrl: http://seq:5341
    depends_on:
      - postgres
      - rabbitmq
      - seq
