### PUT /profiles

PUT {{Voxpop.Core.HostAddress}}/profiles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

{
  "personalInfo": {
    "dateOfBirth": "1989-03-01"
  }
}

### GET /profiles

GET {{Voxpop.Core.HostAddress}}/profiles
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### POST /polls

POST {{Voxpop.Core.HostAddress}}/polls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

{
  "question": "Em quem você vai votar em 2026?",
  "expiresAt": "2027-01-01T00:00:00-03:00",
  "voteMode": 1,
  "access": 1,
  "resultsAccess": 1,
  "resultsVisibility": 1,
  "options": [
    {
      "value": "Ciro Gomes"
    },
    {
      "value": "Lula"
    },
    {
      "value": "Flávio Bolsonaro"
    }
  ]
}

### POST /polls

POST {{Voxpop.Core.HostAddress}}/polls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

{
  "question": "EUA vai invadir a Groenlândia em 2026?",
  "expiresAt": "2026-06-01T00:00:00-03:00",
  "voteMode": 1,
  "access": 1,
  "resultsAccess": 1,
  "resultsVisibility": 1,
  "options": [
    {
      "value": "Sim"
    },
    {
      "value": "Não"
    }
  ]
}

### POST /polls

POST {{Voxpop.Core.HostAddress}}/polls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

{
  "question": "China vai reunificar Taiwan?",
  "expiresAt": "2028-01-01T00:00:00-03:00",
  "voteMode": 1,
  "access": 1,
  "resultsAccess": 1,
  "resultsVisibility": 1,
  "options": [
    {
      "value": "Sim"
    },
    {
      "value": "Não"
    }
  ]
}

### POST /polls

POST {{Voxpop.Core.HostAddress}}/polls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

{
  "question": "Linguagens de programação favoritas?",
  "expiresAt": "2028-01-01T00:00:00-03:00",
  "voteMode": 2,
  "access": 1,
  "resultsAccess": 1,
  "resultsVisibility": 1,
  "options": [
    {
      "value": "C#"
    },
    {
      "value": "Java"
    },
    {
      "value": "Python"
    },
    {
      "value": "C/C++"
    },
    {
      "value": "JavaScript"
    },
    {
      "value": "TypeScript"
    },
    {
      "value": "Rust"
    }
  ]
}

### POST /polls

POST {{Voxpop.Core.HostAddress}}/polls
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

{
  "question": "1 + 1 x (1 + 1)?",
  "voteMode": 1,
  "access": 1,
  "resultsAccess": 1,
  "resultsVisibility": 1,
  "options": [
    {
      "value": "1"
    },
    {
      "value": "2"
    },
    {
      "value": "3"
    },
    {
      "value": "4"
    }
  ]
}

### GET /polls - List polls

GET {{Voxpop.Core.HostAddress}}/polls?page=1&pageSize=50
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### GET /polls - List polls with filters

GET {{Voxpop.Core.HostAddress}}/polls?page=1&pageSize=50&voteMode=1
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### GET /polls - List polls with sorting

GET {{Voxpop.Core.HostAddress}}/polls?page=1&pageSize=50&sortBy=3
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### PUT /polls/{id}/votes/{optionId}

PUT {{Voxpop.Core.HostAddress}}/polls/62380e1e-f65a-4c5e-a4ca-bc72383e3f2b/votes/4e77f7d5-e92f-4b25-85c4-7b78a895f8a7
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### DELETE /polls/{id}/votes/{optionId}

DELETE {{Voxpop.Core.HostAddress}}/polls/e6f524e1-c88a-4a24-ad9e-e3b4eab39095/votes/5015ec54-49f1-418f-9b36-2a35da753e7b
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### PUT /polls/{id}/reactions/{reactionType}

PUT {{Voxpop.Core.HostAddress}}/polls/3614d45f-581a-4073-9bb7-713a3e519df0/reactions/Like
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY

### DELETE /polls/{id}/reactions/{reactionType}

DELETE {{Voxpop.Core.HostAddress}}/polls/3614d45f-581a-4073-9bb7-713a3e519df0/reactions/Like
Accept: application/json
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1Y2RlZTUzZi0xNzA2LTQwNDQtOGRjZi00NDRkNTE4MThhNmQiLCJwaG9uZV9udW1iZXIiOiI1NTExOTQxNzU4NzQ0IiwiZXhwIjoxODY5NTUwMzU5LCJpc3MiOiJ2b3hwb3AtaWRlbnRpdHkiLCJhdWQiOiJ2b3hwb3AtYXBpIn0.cAKHfJogEPZFbgCEqAdypFGJmMtFqmmdVIBKTLGDsMY