// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Voxpop.Core.Infrastructure.Persistence;

#nullable disable

namespace Voxpop.Core.Infrastructure.Migrations
{
    [DbContext(typeof(CoreDbContext))]
    partial class CoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.HasKey("Id");

                    b.HasIndex("Code", "StateId")
                        .IsUnique();

                    b.ToTable("cities", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Continent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("continents", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("ContinentId")
                        .HasColumnType("uuid")
                        .HasColumnName("continent_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.EducationLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("education_levels", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Ethnicity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ethnicities", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Gender", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("genders", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Occupation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("occupations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Religion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("religions", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.State", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<Guid>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.HasKey("Id");

                    b.HasIndex("Code", "CountryId")
                        .IsUnique();

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.CityTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("city_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.ContinentTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("continent_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.CountryTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("country_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.EducationLevelTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("education_level_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.EthnicityTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("ethnicity_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.GenderTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("gender_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.OccupationTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("occupation_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.RaceTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("race_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.ReligionTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("religion_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.ReferenceData.Translations.StateTranslation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id", "Language");

                    b.ToTable("state_translations", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<Guid?>("CountryId")
                        .HasColumnType("uuid")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_of_birth");

                    b.Property<Guid?>("EducationLevelId")
                        .HasColumnType("uuid")
                        .HasColumnName("education_level_id");

                    b.Property<Guid?>("EthnicityId")
                        .HasColumnType("uuid")
                        .HasColumnName("ethnicity_id");

                    b.Property<Guid?>("GenderId")
                        .HasColumnType("uuid")
                        .HasColumnName("gender_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean")
                        .HasColumnName("is_archived");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<Guid?>("OccupationId")
                        .HasColumnType("uuid")
                        .HasColumnName("occupation_id");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uuid")
                        .HasColumnName("race_id");

                    b.Property<Guid?>("ReligionId")
                        .HasColumnType("uuid")
                        .HasColumnName("religion_id");

                    b.Property<Guid?>("StateId")
                        .HasColumnType("uuid")
                        .HasColumnName("state_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.HasIndex("EducationLevelId");

                    b.HasIndex("EthnicityId");

                    b.HasIndex("GenderId");

                    b.HasIndex("OccupationId");

                    b.HasIndex("RaceId");

                    b.HasIndex("ReligionId");

                    b.HasIndex("StateId");

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Voxpop.Core.Domain.UserProfiles.UserProfile", b =>
                {
                    b.HasOne("Voxpop.Core.Domain.ReferenceData.City", null)
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.Country", null)
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.EducationLevel", null)
                        .WithMany()
                        .HasForeignKey("EducationLevelId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.Ethnicity", null)
                        .WithMany()
                        .HasForeignKey("EthnicityId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.Gender", null)
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.Occupation", null)
                        .WithMany()
                        .HasForeignKey("OccupationId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.Race", null)
                        .WithMany()
                        .HasForeignKey("RaceId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.Religion", null)
                        .WithMany()
                        .HasForeignKey("ReligionId");

                    b.HasOne("Voxpop.Core.Domain.ReferenceData.State", null)
                        .WithMany()
                        .HasForeignKey("StateId");
                });
#pragma warning restore 612, 618
        }
    }
}
