### POST /users 

POST {{Voxpop.Identity.HostAddress}}/api/users
Content-Type: application/json

{
  "phoneNumber": "+5511941758744"
}

### POST /verifications

POST {{Voxpop.Identity.HostAddress}}/api/codes
Content-Type: application/json

{
  "target": "+5511941758744",
  "channel": 1
}

### POST /tokens

POST {{Voxpop.Identity.HostAddress}}/api/tokens
Content-Type: application/json

{
  "target": "+5511941758744",
  "channel": 1,
  "code": "123456"
}

### POST /tokens

PUT {{Voxpop.Identity.HostAddress}}/api/tokens
Content-Type: application/json

{
  "token": "eSfXF9Oe00mi1DZYfteSl9kJ/QrDwYMRM3hxd1b2G0IlSrezXqLOqzFlk+08iqN2fAjiMY973pI+vJU9ZvXeXg=="
}