### POST /verifications

POST {{Voxpop.Identity.HostAddress}}/codes/otp
Content-Type: application/json

{
  "target": "+5511941758744",
  "channel": 1
}

### POST /tokens

POST {{Voxpop.Identity.HostAddress}}/tokens/otp
Content-Type: application/json

{
  "target": "+5511941758744",
  "channel": 1,
  "code": "123456"
}

### POST /tokens

PUT {{Voxpop.Identity.HostAddress}}/tokens
Content-Type: application/json

{
  "token": "01KGJ979ZT40W38WK99VV9WWB7.qZAHQaNgqn2dicBLcUCqB5h7bvqWQWi9B4Ehr3eUh0EuamFoBMa1l/rx24OCtL9JrAIhNc0OsS1aZ3vDj4nSJA=="
}